project:
  type: website
  output-dir: docs

website:
  navbar: false

  sidebar:
    style: docked
    pinned: true
    collapse-level: 0
    search: false
    contents:
    - text: "![](images/logo-home_wooden.jpg)"
      href: index.qmd
    - text: Home
      href: index.qmd
    - text: Zeitplan
      href: schedule.qmd
    - text: Location
      href: location.qmd
    - text: About
      href: about.qmd

format:
  html:
    theme: darkly
    # theme: solar
    # theme: slate
    breadcrumb: false
    css: styles.css
    include-before-body:
      - header.html
    toc: false
    grid:
      sidebar-width: 240px
      body-width: 900px

editor: visual