---
title: "Unterkunft"
---

Je nach Absprache wisst ihr schon, wo ihr hingehört. Bei Unklarheiten bitte einfach noch mal an uns wenden. Folgende Optionen gibt es:

---

### Zeltwiese Kranwerk

* Eine gemütliche, ruhige Wiese (wenn keiner schnarcht) direkt auf dem Gelände des Kranwerks
* Dusch- und Toilettencontainer stehen zur Verfügung
* Keine Autos erlaubt
* Zelte am besten schon Freitag zwischen 16:00–18:00 Uhr aufbauen
* Frühstück: 09:00–11:00 Uhr im Saal des Kranwerks

---

### Übernachtung im Auto

* Nur nach Rücksprache, da der Platz auf dem Gelände begrenzt ist
* Autos können erst am späteren Abend auf das Gelände gefahren werden
* Dusch- und Toilettencontainer stehen bei der Zeltwiese zur Verfügung
* Frühstück: 09:00–11:00 Uhr im Saal des Kranwerks

---

### Übernachtung im Bauwagen

* Auf dem Gelände des Kranwerks
* Dusch- und Toilettencontainer stehen bei der Zeltwiese zur Verfügung
* Frühstück: 09:00–11:00 Uhr im Saal des Kranwerks

---

### Pension „Goldene Kugel“

* [https://www.goldene-kugel.de/](https://www.goldene-kugel.de/)
* Adresse: Lange Straße 60, 04683 Naunhof
* Fußweg zum Kranwerk: ca. 1 km
* Unterkunft muss selbst bezahlt werden
* Frühstück: 09:00–11:00 Uhr im Saal des Kranwerks

---

### Hotel Rosengarten

* [https://rosengarten-landhotel.de/](https://rosengarten-landhotel.de/)
* Adresse: Nordstraße 22, 04683 Naunhof
* Fußweg zum Kranwerk: ca. 300 m
* Zimmerbelegung bitte über uns erfragen (Zimmer sind reserviert)
* Unterkunft muss selbst bezahlt werden
* Frühstück: 09:00–11:00 Uhr im Saal des Kranwerks

---



