---
title: "Geschenke"
---
<br>
Uns ist das Wichtigste mit euch zu feiern! Also vorher noch einen Mittagsschlaf gemacht, mit Hunger anreisen, um mit uns lecker zu essen uns dann bis zum Umfallen das Tanzbein schwingen, das wäre das schönste Geschenk von euch an uns.

Bitte nehmt Abstand von Blumengeschenken, Haushaltswaren oder Dekoartikeln. Brauchen wir wirklich nicht ;P

Wer dennoch etwas schenken möchte...

 

### Kuchen

Wer Kapazitäten hat und leidenschaftlich gern bäckt, kann uns gern mit ihren/ seinen Backkünsten verwöhnen. Wir lieben Kuchen!

Sprecht das gern mit uns ab, damit es nicht fünfmal die Schoko-Sahne-Torte wird.

Wenn wir uns Kuchensorten wünschen dürfen, dann gern irgendwas mit Früchten und/oder Streuseln und/oder Pudding/Quark. Bitte verzichtet auf irgendwelche übertriebenen Hochzeitstorten.

### Dessert

Solltet ihr keine großen Kuchenbäcker*innen sein, aber trotzdem etwas kleines zaubern wollen,  
freuen wir uns sehr über einen Beitrag zum Dessert beim Abendbuffet.  
Bitte sprecht auch das gern mit uns ab, damit wir alles gut koordinieren können.  

### Geld

Wer einen Beitrag zu unseren Flitterwochen leisten möchte, kann gern etwas in die Reisekasse einzahlen. Dafür werden wir vor Ort eine Spendenbox bereithalten.

Der Plan ist dann im Jahr 2027 für drei Wochen nach Vietnam zu reisen.